repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/john-hen/Flake8-pyproject
    rev: 1.1.0
    hooks:
      - id: Flake8-pyproject
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language: python
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
