version: "3.8"

x-environment: &env
 environment:
  - POSTGRES_USER=postgres
  - POSTGRES_PASSWORD=postgres
  - POSTGRES_DB=task_manager
  - POSTGRES_HOST=db
  - POSTGRES_PORT=5432
  - SERVER_HOST=0.0.0.0
  - SERVER_PORT=8000
  - APP_TOKEN_SECRET_KEY
  - APP_DOCS_URL


services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    <<: *env
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "psql", "-U", "${POSTGRES_USER:-postgres}", "-d", "${POSTGRES_DB:-task_manager}"]
      timeout: 45s
      interval: 5s
      retries: 15

  app:
    build:
      context: ./app
      args:
        POETRY_ARGS: --no-interaction --no-ansi
    expose:
      - ${SERVER_PORT:-8000}
    <<: *env
    depends_on:
      db:
        condition: service_healthy
    restart: always

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - db
      - app
    environment:
      - MODE=dev
      - HTPASSWD
    restart: always

volumes:
  postgres_data:
