version: "3.8"

services:
  app:
    build:
      context: ./app
      args:
        POETRY_ARGS: --only main --no-interaction --no-ansi

  nginx:
    build:
     context: ./nginx
     args:
       CONF_FILE: nginx.prod.conf
    volumes:
      - certs:/etc/ssl/certs
      - app_static:/var/www/app_static/
    ports:
      - "443:443"

  flower:
    environment:
      - FLOWER_BASIC_AUTH

volumes:
  certs:
  app_static:
