"""003_add_user_id_in_task

Revision ID: 2709611cea32
Revises: ede5789494a2
Create Date: 2022-11-07 18:40:56.546144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2709611cea32"
down_revision = "ede5789494a2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "tasks", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.drop_column("tasks", "user_id")
    # ### end Alembic commands ###
