"""005_alter_active_in_task

Revision ID: ccedef1e58d0
Revises: b9cd3b627099
Create Date: 2022-11-21 23:10:18.804128

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ccedef1e58d0"
down_revision = "b9cd3b627099"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "active", existing_type=sa.BOOLEAN(), nullable=False)


# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "active", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###
