"""006_add_colums_in_tasks

Revision ID: c8698abd94bc
Revises: ccedef1e58d0
Create Date: 2022-11-26 11:48:32.308469

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa

from db.constants import StatusType

# revision identifiers, used by Alembic.
revision = "c8698abd94bc"
down_revision = "ccedef1e58d0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column("status", sqlalchemy_utils.types.choice.ChoiceType(StatusType, impl=sa.Integer()), nullable=True),
    )
    op.add_column("tasks", sa.Column("completion_date", sa.DateTime(), nullable=True))
    op.drop_column("tasks", "active")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks", sa.Column("active", sa.BOOLEAN(), autoincrement=False, nullable=False, server_default=sa.text("true"))
    )
    op.drop_column("tasks", "completion_date")
    op.drop_column("tasks", "status")
    # ### end Alembic commands ###
