"""007_add_table_categories

Revision ID: 26998a1d2247
Revises: c8698abd94bc
Create Date: 2022-11-27 00:15:15.132229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "26998a1d2247"
down_revision = "c8698abd94bc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tasks_categories",
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
    )
    op.add_column("tasks", sa.Column("category_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "tasks", "categories", ["category_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.drop_column("tasks", "category_id")
    op.drop_table("tasks_categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
