"""008_drop_category_id_in_tasks

Revision ID: d0078b7323a9
Revises: 26998a1d2247
Create Date: 2022-11-27 00:36:49.046873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d0078b7323a9"
down_revision = "26998a1d2247"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("tasks_category_id_fkey", "tasks", type_="foreignkey")
    op.drop_column("tasks", "category_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("category_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key("tasks_category_id_fkey", "tasks", "categories", ["category_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###
