name: deploy
on:
  push:
    branches: master
  workflow_run:
    workflows: [linters, testing]
    types:
      - completed
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.VPS_SSH_HOST }}
        username: ${{ secrets.VPS_SSH_USERNAME }}
        key: ${{ secrets.VPS_SSH_SECRET }}
        port: ${{ secrets.VPS_SSH_PORT }}
        script: |
          cd ${{ secrets.PROJECT_PATH }}
          make down
          git pull origin master
          ls
          make build-prod
          make list
